.PHONY: test
test:
	cargo +nightly test

.PHONY: clean
clean:
	cargo clean

.PHONY: build
build:
	cargo +nightly build

.PHONY: release
release:
	cargo +nightly build --release

.PHONY: run
run:
	cargo +nightly run
