version: '2'
services:

  proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - '${WASM_PATH:-../target/wasm32-unknown-unknown/debug/hermit_wasm.wasm}:/etc/hermit.wasm'
    networks:
      - envoymesh
    expose:
      - "8001"
      - "10000"
    ports:
      - "18001:8001"
      - "10000:10000"

  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="Wasm filter test"'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"
    ports:
      - "18080:5678"

networks:
  envoymesh: {}
